# Generated by Django 5.1.6 on 2025-09-06 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100)),
                ('car_model', models.CharField(max_length=100)),
                ('car_image', models.ImageField(upload_to='images/')),
                ('car_price', models.IntegerField()),
            ],
        ),
    ]
